#!/bin/sh
#
# 内存检查脚本
#
# 用法：$0 <testin> <progout> <commands...>

TESTIN="$1"; shift
PROGOUT="$1"; shift

if [ -f "$TESTIN" ]; then
    exec "$@" --gtest_output=xml < "$TESTIN" > "$PROGOUT"
else
    exec "$@" --gtest_output=xml > "$PROGOUT"
fi
