#!/bin/sh
#
# 内存检查脚本
#
# 用法：$0 <testin> <progout> <commands...>

TESTIN="$1"; shift
PROGOUT="$1"; shift
PROG="$1"; shift

if [ -f "$TESTIN" ]; then
    "${PROG}-asan" "$@" < "$TESTIN" > "$PROGOUT" 2> asan.out
else
    "${PROG}-asan" "$@" > "$PROGOUT" 2> asan.out
fi
exit 0