#!/bin/bash

# Scala compile wrapper-script for 'compile.sh'.
# See that script for syntax and more info.
#
# This script requires that scala is installed in the chroot.

DEST="$1" ; shift
SOURCE_FILES="$1"; shift
IFS=':' read -ra SOURCE_FILES_SPLITTED <<< "$SOURCE_FILES"
MAINSOURCE="${SOURCE_FILES_SPLITTED[0]}"

scalac "${SOURCE_FILES_SPLITTED[@]}"
EXITCODE=$?
[ "$EXITCODE" -ne 0 ] && exit $EXITCODE

MAINCLASS="${ENTRY_POINT:-$(basename "$MAINSOURCE" .scala)}"

# Report the entry point, so it can be saved, e.g. for later replay:
if [ -z "$ENTRY_POINT" ]; then
	echo "Info: detected entry_point: $MAINCLASS"
fi

cat > "$DEST" <<EOF
#!/bin/sh
# 运行路径不一定是编译目录，因此我们需要切换到编译目录下运行，否则会找不到文件
if [ "\${0%/*}" != "\$0" ]; then
    cd "\${0%/*}"
fi

exec scala '$MAINCLASS' "\$@"
EOF

chmod a+x "$DEST"

exit 0