name: Build

on: [push, pull_request]

jobs:
  build:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2
        with: 
          submodules: "recursive"

      - name: Install Packages
        run: sudo hack/install_packages.sh -y

      - name: Build Judge System
        run: hack/build.sh
      
      - name: Build debian package
        run: cd build && ninja package
#       - name: Copy Binaries
#         run: |
#             mkdir -p bin runguard/bin
#             cp build/bin/judge-system bin
#             cp build/runguard/bin/runguard runguard/bin
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: Runnable Package
#           path: |
#             bin/judge-system
#             runguard/bin/runguard
#             exec
#             script
#             config
#             prepare.sh
#             run.sh
            
