name: Build

on: [push, pull_request]

jobs:
  build:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-latest
    container: debian:bullseye
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2
        with: 
          submodules: "recursive"
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install Packages
        run: hack/install_packages.sh -y

      - name: Build Judge System
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          hack/build.sh -DCMAKE_BUILD_TYPE=RelWithDebInfo
      
      - name: Build debian package
        run: cd build && ninja package
